services:
  api:
    container_name: nestcake-api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - apps/api/.env
    volumes:
      - ./apps/api/public/uploads:/app/apps/api/public/uploads

  web:
    container_name: nestcake-web
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - apps/web/.env
    depends_on:
      - api