export enum NotificationType {
  NEW_PROPOSAL = 'NEW_PROPOSAL',
  ORDER_ACCEPTED = 'ORDER_ACCEPTED',
  ORDER_REJECTED = 'ORDER_REJECTED',
  PAYMENT_CONFIRMATION = 'PAYMENT_CONFIRMATION',
  ORDER_IN_PROGRESS = 'ORDER_IN_PROGRESS',
  ORDER_READY = 'ORDER_READY',
  ORDER_COMPLETED = 'ORDER_COMPLETED',
  PICKUP_REMINDER = 'PICKUP_REMINDER',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
}
